# Generated by Django 2.0rc1 on 2018-02-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('side', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('type', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Sides'),
        ),
        migrations.AddField(
            model_name='ship',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Types'),
        ),
    ]
