# Generated by Django 2.0rc1 on 2018-02-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sides',
            new_name='Side',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
