# Generated by Django 2.0rc1 on 2018-02-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180218_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='type',
        ),
        migrations.AddField(
            model_name='ship',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.Type'),
            preserve_default=False,
        ),
    ]
